#ifndef JASYNCRPC_VALIDATION_RETCODES_H
#define JASYNCRPC_VALIDATION_RETCODES_H

enum eValidationRetCodes
{
    VALIDATION_OK = 0x0,
    VALIDATION_METHODNOTFOUND = 0x1,
    VALIDATION_NOTAUTHORIZED = 0x2
};

#endif // JASYNCRPC_VALIDATION_RETCODES_H
