#ifndef JASYNCRPC_RETCODES_H
#define JASYNCRPC_RETCODES_H

enum eRetCodes {

    METHOD_RET_CODE_SUCCESS = 0,
    METHOD_RET_CODE_UNAUTHENTICATED = -9994,
    METHOD_RET_CODE_INVALIDLOCALAUTH = -9995,
    METHOD_RET_CODE_TIMEDOUT = -9996,
    METHOD_RET_CODE_INVALIDAUTH = -9997,
    METHOD_RET_CODE_SERVERMEMORYFULL = -9998,
    METHOD_RET_CODE_METHODNOTFOUND = -9999

};

#endif // JASYNCRPC_RETCODES_H
